import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';

const source=name=>readFileSync(new URL('../public/'+name,import.meta.url),'utf8');
const tick=()=>new Promise(r=>setTimeout(r,30));
async function fixture(){
  const dom=new JSDOM(source('index.html'),{runScripts:'outside-only',pretendToBeVisual:true,url:'https://sofer.primainsurance.tech'});
  const w=dom.window;w.HTMLElement.prototype.scrollIntoView=function(){};w.confirm=()=>true;
  w.eval(source('core.js'));const SS=w.SS;
  const layout={id:'test-layout',status:'draft',geometry:{line_width_mm:130,lines_per_amud:42,baseline_pitch_mm:8},summary:{total_amudim:2,total_lines:84},lines:Array.from({length:84},(_,i)=>({id:String(i),amud:Math.floor(i/42)+1,line_index:i%42+1,text:'בראשית ברא',words:[],leftover_mm:0}))};
  SS.api={listSources:async()=>[{id:'s',name:'Test book'}],listProfiles:async()=>[{id:'p',name:'Test measurements'}],listGeometries:async()=>[{id:'g',name:'Test columns'}],listPatterns:async()=>[],listLayouts:async()=>[],getProfile:async()=>({id:'p'}),session:async()=>({}),getLayout:async()=>layout,computeLayout:async()=>({layout_id:layout.id}),exportLayout:async()=>({kind:'text',text:'{}',filename:'layout.json'})};
  let printed=0;w.print=()=>{printed++;assert.equal(SS.workspace.current(),'layout');assert.equal(w.document.querySelectorAll('.line').length,84);};
  for(const file of ['tikkun.js','stretch.js','export.js'])w.eval(source(file));
  const ready=new Promise(resolve=>SS.bus.on('app:ready',resolve));w.eval(source('app.js'));await ready;
  const load=async()=>{SS.state.active.layoutId=layout.id;SS.state.layout=layout;SS.bus.emit('layout:loaded',layout);await tick();};
  return{dom,w,SS,layout,load,printed:()=>printed};
}
test('four main tabs with one visible workspace; old rails and drawer no longer occupy space',async()=>{const f=await fixture();try{const d=f.w.document;assert.equal(d.querySelectorAll('#workspace-tabs [role=tab]').length,4);assert.equal(d.querySelectorAll('.workspace-view:not([hidden])').length,1);assert.equal(d.getElementById('workbench').hidden,true);assert.equal(d.getElementById('lower-bench').hidden,true);for(const view of ['setup','layout','review','download']){f.SS.workspace.open(view);assert.equal(d.querySelector('.workspace-view:not([hidden])').id,'view-'+view);assert.equal(d.querySelectorAll('#workspace-tabs [tabindex="0"]').length,1);}assert.equal(d.querySelector('#view-review .stretch-book')!==null,true);assert.equal(d.querySelector('#view-layout .stretch-book'),null);}finally{f.dom.window.close();}});
test('tab changes preserve form nodes and unsaved values',async()=>{const f=await fixture();try{const d=f.w.document,input=d.createElement('input');input.value='unsaved measurement';d.getElementById('calibration-body').append(input);f.SS.workspace.open('setup','calibration');f.SS.workspace.open('review');f.SS.workspace.open('setup','calibration');assert.equal(d.querySelector('#calibration-body input'),input);assert.equal(input.value,'unsaved measurement');assert.equal(d.querySelector('#section-setup-calibration').hidden,false);}finally{f.dom.window.close();}});
test('single line editor closes without changing page, zoom or layout',async()=>{const f=await fixture();try{await f.load();const d=f.w.document;f.SS.workspace.open('layout');d.querySelector('[aria-label="Next page"]').click();const zoom=d.querySelector('[aria-label="Preview zoom"]');assert.equal(zoom.value,'width');zoom.value='page';zoom.dispatchEvent(new f.w.Event('change'));f.SS.bus.emit('line:selected',{raw:f.layout.lines[42]});assert.equal(d.getElementById('line-editor').hidden,false);d.querySelector('[aria-label="Close line editor"]').click();assert.equal(d.getElementById('line-editor').hidden,true);assert.equal(d.getElementById('stretch-inspector').hidden,true);assert.equal(d.querySelector('[aria-label="Preview page"]').value,'1');assert.equal(zoom.value,'page');assert.equal(f.SS.state.layout,f.layout);}finally{f.dom.window.close();}});
test('compute goes to Layout; reload keeps the Review tool selected',async()=>{const f=await fixture();try{await f.SS.app.compute();assert.equal(f.SS.workspace.current(),'layout');f.SS.workspace.open('review','stretch');await f.SS.app.reloadLayout(f.layout.id);assert.equal(f.SS.workspace.current(),'review');assert.equal(f.w.document.getElementById('section-review-stretch').hidden,false);}finally{f.dom.window.close();}});
test('legacy links route to the correct workspace and tools',async()=>{const f=await fixture();try{f.SS.activateDrawer('layouts');assert.equal(f.SS.workspace.current(),'setup');assert.equal(f.w.document.getElementById('section-setup-layouts').hidden,false);f.SS.activateDrawer('compare');assert.equal(f.SS.workspace.current(),'review');assert.equal(f.w.document.getElementById('section-review-compare').hidden,false);f.SS.bus.emit('jump:line',{amud:1,line:1});assert.equal(f.SS.workspace.current(),'layout');}finally{f.dom.window.close();}});
test('keyboard tab navigation and focus mode have a working exit',async()=>{const f=await fixture();try{const d=f.w.document;d.getElementById('tab-setup').dispatchEvent(new f.w.KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}));assert.equal(f.SS.workspace.current(),'layout');assert.equal(d.activeElement.id,'tab-layout');f.SS.tikkun.setExpanded(true);assert.equal(d.body.classList.contains('document-focus'),true);f.SS.workspace.open('review');assert.equal(d.body.classList.contains('document-focus'),false);}finally{f.dom.window.close();}});
test('Download prepares every page in visible Layout, then returns after print',async()=>{const f=await fixture();try{await f.load();f.SS.workspace.open('download');await f.SS.export.printLayout();assert.equal(f.printed(),1);f.w.dispatchEvent(new f.w.Event('afterprint'));assert.equal(f.SS.workspace.current(),'download');assert.equal(f.w.document.querySelectorAll('.line').length,84);assert.match(f.w.document.getElementById('download-summary').textContent,/2 columns.*84 lines/);}finally{f.dom.window.close();}});
test('study export restrictions survive the Download redesign',async()=>{const f=await fixture();try{f.layout.summary.study_preview=true;await f.load();f.SS.workspace.open('download');await f.SS.export.printLayout();assert.equal(f.printed(),0);assert.equal(f.SS.workspace.current(),'download');for(const button of f.w.document.querySelectorAll('#export-controls button'))assert.equal(button.disabled,true);assert.match(f.w.document.getElementById('download-summary').textContent,/Export blocked/);}finally{f.dom.window.close();}});
